### ISSUE TITLE
Eu, como desenvolvedor, desejo Elaborar RoadMap para organizar as metas de desenvolvimento do projeto

### ISSUE THREAD

**Issue by luis-gustavo** [fga-gpp-mds/2018.1_Nexte#10]
### Descrição
O roadmap dará uma macro visão sobre o planejamento do projeto em cada _sprint_ 

### Critérios de Aceitação

 - [x] Separar Sprints por Release
 - [x] Alocar histórias de usuário em cada sprint

**Comment by luis-gustavo** [comment]
@Geovannioj  Adicione a descrição e os critérios de aceitação dessa issue conforme o template proposto porfavor.

**Comment by Geovannioj** [comment]
Descrição e critérios de aceitação adicionados.
