### ISSUE TITLE
Eu, como Usuário, desejo editar meu  perfil para atualizar minhas informações.

### ISSUE THREAD

**Issue by gabrielalbino** [fga-gpp-mds/2018.1_Nexte#102]
## Descrição

Essa issue adicionará na tela do perfil, um botão para ir para outra tela afim de alterar as informações do usuário logado.

## Critérios de Aceitação

- [ ] Adicionar botão para alterar informações de perfil;
- [ ] Adicionar usuário logado fictício num singleton para controlar as informações;
- [ ] Adicionar campos para preencher na tela após clicar ao botão;
- [ ] Alterar as informações no singleton e voltar a tela de perfil, mostrando as novas informações

**Comment by gabrielalbino** [comment]
@guibaldissera @miguelpimentel @luis-gustavo @Geovannioj  pra atualizar os dados da minha viewProfile ao usuário clicar no 'atualizar' dentro da edit profile eu preciso de uma referencia dessa classe que seria passada atraves da router, não?
Como eu faço pra chamar um método (por exemplo ShowProfileInteractor.updateUserData()) a partir da minha editprofile?

**Comment by guibaldissera** [comment]
Então... Lembra no sábado que comentei algo sobre ciclo de vida das activities? (lifecycle)
Estava dando uma olhada aqui, e acredito que a forma mais tranquila de se fazer isso agora, seria usar dos métodos do lifecycle...

Deem uma olhada e vejam se sai algo daí... qualquer coisa direciono um pouco mais a solução kkkk
O ponto é que não seria interessante mexermos com rotas nesse momento, e em teoria, quando você clicar em "atualizar", deve ser fechada a activity de editar voltando automaticamente para a activity anterior. Não deve ser feito uma nova chamada ou instanciação para a activity de perfil.

Esse link, da documentação do android, explica bem sobre isso:
https://developer.android.com/guide/components/activities/activity-lifecycle.html

Aqui tem um diagrama legal sobre o lifecycle
<img width="687" alt="captura de tela 2018-04-11 as 00 22 04" src="https://user-images.githubusercontent.com/17801101/38594863-ddd8357e-3d1e-11e8-9826-49c97bff1800.png">

**Comment by gabrielalbino** [comment]
@guibaldissera Saquei, onResume ftw! Valeu, tu é fera!
