### ISSUE TITLE
Eu, como Usuário, gostaria de poder expandir as células do ranking para visualizar mais informações.

### ISSUE THREAD

**Issue by gabrielalbino** [fga-gpp-mds/2018.1_Nexte#105]
## Descrição

Essa issue objetiva incrementar a funcionalidade de ranking, expandindo as células de cada usuário para mostrar mais informações.

## Critérios de Aceitação
- [ ] Refatorar o ranking com a arquitetura (Utilizar RecycleView na View e seus adapters) seguindo o modelo do Feed; 
- [ ] Adicionar a expansão e compressão ao clicar na célula do List View;

**Comment by miguelpimentel** [comment]
Yeah!


2018-04-09 19:19 GMT-03:00 Letícia Meneses <notifications@github.com>:

**Comment by mbslet** [comment]
Senhores, temos algumas dúvidas aqui, espero que possam dar um help em compreendê-las.

* FeedPresenter - (linha 37) for (activity in activities): Da onde veio essa activity

* FeedPresenter - (linha 35) MutableList<FeedModel.FeedActivityFormatted> = mutableListOf(): Por que a MutableList foi usada? 

Agradeço :D

**Comment by mbslet** [comment]
Oi, estava vendo aqui no modelo da FeedScene e vi que vocês trabalharam com o adpter e context normal porém dentro da FeedView, e no caso antigo do Ranking estava sendo usado na Presenter. Devemos seguir o exemplo e usar na View ou foi um motivo especifico  da Feed?

Detalhe: Estou perguntando para ficar 100% segura porque segunda a explicação de hoje, tudo foi feito na View mesmo, só quero ter certeza antes mudar tudo

**Comment by guibaldissera** [comment]
Certo, sobre as primeiras dúvidas, referente a linha 35 e 37 da FeedPresenter, foram respondidas pessoalmente hoje 12h, qualquer coisa posso detalhar aqui.

Em relação a Adapter vamos lá.
Lembram que comentei que anteriormente a variável 'context' era enviada camada à camada até chegar na presenter? A context é basicamente o contexto que a view está inserida. Isso está totalmente ligada a nossa camada de View. Por esse motivo, context não deveria existir em outras camadas a não ser a própria View.
Outro ponto, anteriormente o controle da adapter era feito na Presenter, lembram que nossa Presenter tem como objetivo apenas formatar os dados vindos da Worker por meio da Model.Response, gerando então uma Model.ViewModel? Nenhum outro objetivo está presente na Presenter, portanto, controlar a View também não.
Por esses motivos todo o controle de Views, deve ser feito na própria View ou em classes, como a FeedAdapter que está no contexto da View e que foi criada para desacoplar o controle da RecyclerView da View em si.

Não sei se ficou claro, qualquer coisa perguntem novamente kkkkkk

**Comment by mbslet** [comment]
Lembrei disso que tu disse mais cedo, e fez todo sentido de novo haha, obrigada!

**Comment by mbslet** [comment]
![screenshot from 2018-04-11 12-37-21](https://user-images.githubusercontent.com/30835147/38627329-1de8c96a-3d85-11e8-8a2d-3a193b0a3449.png)

Tentamos colocar a imagem que está na pasta da mipmap, do mesmo modo da Feed, na Model ela é do tipo Int mas no erro requer uma string, podem me explicar?
