### ISSUE TITLE
Eu, como usuário, desejo visualizar um gráfico de vitórias mensais na tela de perfil

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#111]
## Descrição

Essa issue tem como objetivo adicionar um gráfico de vitórias e derrotas na tela de perfil ao longo dos meses.

## Critérios de Aceitação

- [ ] Adicionar framework de Chart no projeto (MPAndroidChart);
- [ ] Adicionar o gráfico na tela de perfil;
- [ ] Customizar o gráfico para mostrar as informações necessárias.
- [ ] Adicionar testes;
- [ ] Adicionar comentários de código.

**Comment by lorranyh** [comment]
Vocês podem mandar a imagem de como ficaria o gráfico no aplicativo?

**Comment by miguelpimentel** [comment]
Vou mandar agora

**Comment by miguelpimentel** [comment]
[![Screen_Shot_2018-04-23_at_21.03.55.png](https://s17.postimg.cc/8khnwa9pb/Screen_Shot_2018-04-23_at_21.03.55.png)](https://postimg.cc/image/yssslntsr/)

**Comment by miguelpimentel** [comment]
[![IMG_0903_D5_F5_ADEB-1.jpg](https://s17.postimg.cc/cguzsbkf3/IMG_0903_D5_F5_ADEB-1.jpg)](https://postimg.cc/image/lbvu2u97f/)

**Comment by mbslet** [comment]
![screenshot from 2018-04-26 10-17-29](https://user-images.githubusercontent.com/30835147/39308183-359bf1ba-493b-11e8-8811-46474d605991.png)
Esse é o código para plotar o gráfico

e assim está no xml: 
![screenshot from 2018-04-26 10-19-58](https://user-images.githubusercontent.com/30835147/39308273-68286140-493b-11e8-9633-d1bfa7cdfe97.png)

**Comment by mbslet** [comment]
Vocês saberiam dizer o porquê de não funcionar o gráfico?

**Comment by miguelpimentel** [comment]
@mbslet  e @lorranyh, pelo que olhei parece correto, entretanto acredito que vocês poderiam seguir esse tutorial:  https://www.studytutorial.in/android-line-chart-or-line-graph-using-mpandroid-library-tutorial. Está tudo muito estruturado e tá confuso de entender. Eu comecei a fazer aqui em Kotlin, se não conseguirem me avise. Não consegui terminar porque ainda tenho muita coisa de histórias para fazer. Se não conseguirem fazer, me chamem!

**Comment by lorranyh** [comment]
Então, o nosso array de string não está funcionando, definimos o tipo dele, o gráfico aparece, mas qnd fizemos alterações para adaptar ao estilo de gráfico do aplicativo ele não vai 
![image](https://user-images.githubusercontent.com/31133947/39386292-57643086-4a4a-11e8-957a-436603f83bdf.png)

Na parte que o eixo x, deve mostrar os meses das partidas ganhas.

**Comment by lorranyh** [comment]
/home/lorrany/Imagens/Captura de tela de 2018-04-27 19-05-44.png

**Comment by lorranyh** [comment]
![image](https://user-images.githubusercontent.com/31133947/39387159-70b962f0-4a4e-11e8-96ff-79ce2e71acec.png)
Na verdade, ele tá assim

**Comment by lorranyh** [comment]
![image](https://user-images.githubusercontent.com/31133947/39387182-9016884e-4a4e-11e8-84ab-a4c4a9cacb98.png)

**Comment by lorranyh** [comment]
![image](https://user-images.githubusercontent.com/31133947/39387205-b5185334-4a4e-11e8-883c-4e442168c1ab.png)

**Comment by miguelpimentel** [comment]
@lorranyh,  o problem é que vocês não consegue colocar os valores esperados, tipos pontos cartesianos(x,y)?

**Comment by mbslet** [comment]
o problema é que temos dados no eixo X, ali no xVals, mas não conseguimos usa-lo no LineDataSets, estamos tentando entender onde ele vai, porque se não for usado não mostra mesmo

**Comment by miguelpimentel** [comment]
@mbslet, então, são properties que você configura, e para isso tem que olhar a documentação. Aquele código que passei para vocês não tava legal quando falava que setava o eixo Y, afinal ele configurava os valores do gráfico, pontos(x,y).

**Comment by miguelpimentel** [comment]
```

//
//  DrawCharts.swift
//  Nexte
//
//  Created by Miguel Pimentel on 24/11/17.
//  Copyright © 2017 Nex.te. All rights reserved.
//

import UIKit
import Charts


class DrawCharts {

    // MARK: - Constructor
    
    init() {}

    
    // MARK: - Create Chart
    
    func createChartWithOneContentLine(lineChartView: LineChartView, data: [Double], color: UIColor) {
        
        lineChartView.delegate = self
        
        let dataEntrie = self.loadData(values: data)
        let matchesDataSet = self.setChartDataSet(dataEntries: dataEntrie, color: color)
        let chartDataSets = [matchesDataSet]
        let chartData = self.setChartData(chartDataSets: chartDataSets)
        
        self.setLineChartView(lineChartView: lineChartView, chartData: chartData, inverted: true)
    }
    
    func createChartWithThreeContentLines(lineChartView: LineChartView, data: [Double], colors: [UIColor]) {
        
        lineChartView.delegate = self
        
        let firstDataEntry = self.loadData(values: [0, 2, 1, 5])
        let secondDataEntry = self.loadData(values: [2, 4, 1, 3,])
        let thirdDataEntry = self.loadData(values: [2, 6, 2, 8])
        
        let matchesDataSet = self.setChartDataSet(dataEntries: firstDataEntry, color: colors[0])
        let winsDataSet = self.setChartDataSet(dataEntries: secondDataEntry, color: colors[1])
        let losesDataSet = self.setChartDataSet(dataEntries: thirdDataEntry, color: colors[2])
        
        let chartDataSets = [matchesDataSet, winsDataSet, losesDataSet]
        let chartData = self.setChartData(chartDataSets: chartDataSets)
        
        self.setLineChartView(lineChartView: lineChartView, chartData: chartData)
    }
    
    // MARK: - Layout

    // Set Chart Values to Axis
    func loadData(values: [Double]) -> [ChartDataEntry] {
        
        var dataEntries = [ChartDataEntry]()
        
        for i in 0..<values.count {
            let data = ChartDataEntry(x: Double(i), y: values[i])
            dataEntries.append(data)
        }
        
        return dataEntries
    }
    
    // Set Chart Line Preferences
    func setChartDataSet(dataEntries: [ChartDataEntry], color: UIColor) -> LineChartDataSet {
        
        let chartDataSet = LineChartDataSet(values: dataEntries, label: "Chart")
        let customGray = UIColor(red: 0.1765, green: 0.1765, blue: 0.1765, alpha: 1.0) // Chart Background color
        
        chartDataSet.colors = [color]
        chartDataSet.drawCirclesEnabled = false
        chartDataSet.drawCircleHoleEnabled = false
        chartDataSet.circleColors = [UIColor(named: "coral")!]
        chartDataSet.circleHoleColor = customGray
        chartDataSet.circleRadius = 5.0
        chartDataSet.lineWidth = 4.0
        chartDataSet.mode = .cubicBezier
        chartDataSet.cubicIntensity = 0.2
        chartDataSet.drawValuesEnabled = false // Puts value upside the line
        
        return chartDataSet
    }
    
    // Add Lines to Chart
    func setChartData(chartDataSets: [LineChartDataSet]) -> LineChartData {
        
        let chartData = LineChartData()
        chartData.setDrawValues(true)
        
        for data in chartDataSets {
             chartData.addDataSet(data)
        }
        
        return chartData
    }
    
    // Settup Chart Preferences
    func setLineChartView(lineChartView: LineChartView, chartData: LineChartData, inverted: Bool = false) {
 
        // General
        lineChartView.data = chartData
        lineChartView.noDataText = "No data available"
        lineChartView.chartDescription = nil
        lineChartView.legend.enabled = false
       
        lineChartView.xAxis.drawGridLinesEnabled = false
        lineChartView.leftAxis.drawGridLinesEnabled = false
        
        lineChartView.minOffset = 20.0  // padding around the chart
    
        // Disable scale
        lineChartView.scaleXEnabled = false
        lineChartView.scaleYEnabled = false
        
        // Configure grid Lines
        lineChartView.rightAxis.gridLineWidth = 1.0
        lineChartView.rightAxis.axisLineWidth = 3.0
        
        // Axis X
        let axisX = lineChartView.xAxis
        axisX.labelPosition = .bottom
        axisX.labelFont =  NSUIFont.init(name: "HelveticaNeue-Light", size: 14)!
        axisX.labelTextColor = UIColor(named: "gray")!
        axisX.gridLineWidth = 1.0
        axisX.axisLineWidth = 0
        
        // Add Labels to Chart
        let months = ["Set", "Out", "Nov", "Dez", "Jan", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set"]

        axisX.valueFormatter = IndexAxisValueFormatter(values: months)
        axisX.granularity = 1

        // Axis Y
        let rightAxisY = lineChartView.rightAxis
        rightAxisY.enabled = false
        
        let leftAxisY = lineChartView.leftAxis
        leftAxisY.labelFont = NSUIFont.init(name: "HelveticaNeue-Light", size: 14)!
        leftAxisY.labelTextColor = UIColor(named: "gray")!
        leftAxisY.gridLineWidth = 1.0
        leftAxisY.axisLineWidth = 0

        // FIXME: This is just to deliver the app. Refactor this whole shit
        if inverted { // Used to invert the Ranking graph
            leftAxisY.inverted = inverted
            leftAxisY.axisMinimum = 1
            leftAxisY.axisRange = 10
            leftAxisY.axisMaximum = 20
        }

        
        lineChartView.animate(yAxisDuration: 1.5)
    }
}

extension DrawCharts: ChartViewDelegate {
    
    func chartValueSelected(_ chartView: ChartViewBase, entry: ChartDataEntry, highlight: Highlight) { }
    
    func chartScaled(_ chartView: ChartViewBase, scaleX: CGFloat, scaleY: CGFloat) { }
    
    func chartTranslated(_ chartView: ChartViewBase, dX: CGFloat, dY: CGFloat) { }
    
    func chartValueNothingSelected(_ chartView: ChartViewBase) { }
}


````

**Comment by miguelpimentel** [comment]
Esse código aí em cima utilizei para configurar o chart para nossas configurações. Eu me inspirei na documentação do Android para fazê-lo, visto que ela é 283128371 vezes maior que a do iOS.  Acredito que o que está procurando é isso:

```
  // Add Labels to Chart
        let months = ["Set", "Out", "Nov", "Dez", "Jan", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set"]

        axisX.valueFormatter = IndexAxisValueFormatter(values: months)
        axisX.granularity = 1
```
Lembrando, que tudo que vocês fazerem desde a parte que mandei ontem é leitura da wiki do Framework,  pois são customizações e não estarão em tutoriais.

**Comment by mbslet** [comment]
` axisX.valueFormatter = IndexAxisValueFormatter(values: months) `

eu usei algo do tipo, mas o app fechava

**Comment by mbslet** [comment]
Fiz exatamente algo do tipo

**Comment by mbslet** [comment]
![screenshot from 2018-04-27 22-03-39](https://user-images.githubusercontent.com/30835147/39390150-069f7fda-4a67-11e8-83cd-566225460aaa.png)

Foi isso que eu tinha feito só que no lugar de `        axisX.valueFormatter = IndexAxisValueFormatter(values: months)
`
Era 

`val formatter = object : IAxisValueFormatter() {
Override
    public String getFormattedValue(float value, AxisBase axis) {
        return lastMonths[(int) value];
    }`

E ele fechava o app.

Coloquei desse jeito que tu mandou

`axisX.valueFormatter = IndexAxisValueFormatter(values: months)`

E ele aceitou de boas :D só está zoado o gráfico mas está mostrando string
![whatsapp image 2018-04-27 at 22 08 33](https://user-images.githubusercontent.com/30835147/39390273-81ebb98c-4a68-11e8-9cdd-469145dc907f.jpeg)

Da forma que eu fiz eu fechava o app ao clicar no perfil...
Obrigada demais!!

**Comment by lorranyh** [comment]
Então, na escala do eixo Y, ele não está apresentando uns valores bem concretos, a questão é como defini-los segundo os valores que colocamos nos pontos do array, estamos enviando um PR, porém com essas observações, lembrando que os testes, como comentado na daily, seriam proposto após a análise do PR
