### ISSUE TITLE
Eu, como usuário, desejo ver a lista de comentários de uma atividade no feed

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#112]
## Descrição

Essa issue tem como objetivo adicionar uma tela com a lista de comentários pertencente a uma atividade do feed.

## Critérios de Aceitação

- [x] Número de comentários na atividade;
- [x] Ao clicar na label da quantidade, abrir uma tela com os comentários;
- [x] Mostrar a lista dos comentários na tela que abriu (Foto e nome do usuário, comentário, data dele, botão de denunciar e excluir comentário);
- [x] Adicionar testes na scene; (Manter a % de cobertura de testes ou aumentar).
- [x] Adicionar comentários.

**Comment by aleronupe** [comment]
![captura de tela de 2018-04-25 22-54-51](https://user-images.githubusercontent.com/37146204/39281562-b46d89f0-48db-11e8-8557-f22258817fe0.png)

@luis-gustavo Por quê o teste da _presenter_ verifica se a response chegou na interface da _presenter_ mas não verifica se a passagem pela _worker_ aconteceu? Devemos implementar a passagem pela _worker_ ?

**Comment by luis-gustavo** [comment]
@aleronupe @larissa-sales  Então a passagem pela worker acontece ao chamar

```Kotlin
this.interactor?.recentComments(request)
```

Para chegar uma response(do tipo CommentsViewModel.Response) tem que, necessariamente, ter passado pela worker. Não faz muito sentido testar nada dentro da worker pois isso é testado no próprio teste da worker, o importante é ver se o request que é passado pela interactor vai resultar na chegada de um response na presenter. Deu pra entender ?
