### ISSUE TITLE
Eu, como usuário, desejo visualizar um desafio ativo ao usuário.

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#114]
## Descrição

Essa issue destina-se a adicionar uma tela onde seja possível visualizar um desafio com os campos para adicionar resultado, data, hora e para ver as informações básicas dos tenistas envolvidos.

## Critérios de Aceitação

- [x] Ao abrir a tela, deve-se passar o código do desafio da tela originária para a tela a ser aberta, usando os métodos de passagem de parâmetros para uma Intent;
- [x] Na tela do desafio, deve-se mostrar a foto e o nome dos dois tenistas (Desafiado e Desafiante);
- [ ] Deve existir um Segmented Control para mudar a forma que o resultado será inserido;
- [x] Deve-se criar uma célula re-usável que receba as informações que devem ser impressas nela (Exemplificarei nos comentários quais informações devem ser alteradas na célula programaticamente), e essa deve conter uma label informando qual é o Set em questão, e dois inputs para o usuário colocar os games do desafiante e do desafiado;
- [x] Deve existir um campo para selecionar a data e outro campo com a hora que o jogo foi jogado;
- [ ] O campo de data deve vir preenchido com a data atual;
- [x] O campo de hora deve vir vazio, sem hora preenchida por padrão;
- [x] Deve-se adicionar um botão para cancelar o desafio;
- [x] Deve-se adicionar um botão para enviar o resultado, por padrão ele precisa estar em modo não enabled;
- [ ] Não precisa fazer o Segmented Control funcionar, é apenas necessário colocá-lo na tela.

**Comment by guibaldissera** [comment]
Aqui estão exemplificadas as células dinâmicas que foi citado no critério de aceitação. 
<img width="369" alt="captura de tela 2018-04-28 as 12 14 01" src="https://user-images.githubusercontent.com/17801101/39397979-d900dc28-4add-11e8-81bb-fe1101d514a9.png">
<img width="368" alt="captura de tela 2018-04-28 as 12 14 09" src="https://user-images.githubusercontent.com/17801101/39397980-d9225358-4add-11e8-9b56-d373be4b1fb8.png">
<img width="366" alt="captura de tela 2018-04-28 as 12 14 16" src="https://user-images.githubusercontent.com/17801101/39397981-d9417cec-4add-11e8-8e03-13c9d5de1fdc.png">
<img width="370" alt="captura de tela 2018-04-28 as 12 13 56" src="https://user-images.githubusercontent.com/17801101/39397982-d9623234-4add-11e8-88e8-758e370ca555.png">
<img width="368" alt="captura de tela 2018-04-28 as 12 13 51" src="https://user-images.githubusercontent.com/17801101/39397983-d991cbd4-4add-11e8-9ddb-2473a9f2496e.png">
<img width="370" alt="captura de tela 2018-04-28 as 12 13 44" src="https://user-images.githubusercontent.com/17801101/39397984-d9b2ac50-4add-11e8-9aee-4fe4d190bc82.png">

**Comment by guibaldissera** [comment]
Aqui está um exemplo do Segmented Control usado para selecionar o tipo de resultado:
<img width="361" alt="captura de tela 2018-04-28 as 12 14 29" src="https://user-images.githubusercontent.com/17801101/39398001-07f49ce0-4ade-11e8-93cb-f730d80f8d59.png">
<img width="352" alt="captura de tela 2018-04-28 as 12 14 22" src="https://user-images.githubusercontent.com/17801101/39398002-0812843a-4ade-11e8-8b71-94a7e8b3a613.png">

**Comment by guibaldissera** [comment]
E aqui é um exemplo da tela num geral... contendo o segmented control, as células de resulado, os jogares, a data e hora, e o botão de cancelar partida.
![simulator screen shot - iphone 7 - 2018-03-07 at 00 56 38](https://user-images.githubusercontent.com/17801101/39398015-2e92e0d2-4ade-11e8-9758-a6e29e70c6c0.png)

**Comment by mbslet** [comment]
Precisa de uma cena nova?

**Comment by guibaldissera** [comment]
Pode ser, façam uma scene nova com o nome de MatchScene

**Comment by aleronupe** [comment]
O Código do desafio deve ser o requesta da nossa função de displayScene, certo?

**Comment by mbslet** [comment]
"e o que a gente quer saber é se esse identificador de desafio é o request que a gente vai passar, porque foi assim que pensamos em fazer" - Alexandre

**Comment by guibaldissera** [comment]
Isso... deve ser... O Request é o Request kkkkk... identificador não é o Request... o identificador é um atributo que vai dentro da classe de Request.

**Comment by mbslet** [comment]
Eu buguei um pouco porque temos que fazer "informações" separadas dentro da mesma recyclerview, mas na nossa response vem todas elas, pq eu tava achando que seriam várias responses nesse caso...

**Comment by guibaldissera** [comment]
Não, as informações vem tudo numa mesma response... a diferença é que as informações específicas vão ser mostradas em células diferentes dentro de uma mesma recycler view

**Comment by aleronupe** [comment]
@guibaldissera rola alguém mandar um videozinho dessa parte funcionando pra gente ter uma ideia geral das expansões e de como se organiza cada set? Eu sei que não é um dos critérios de aceitação, mas acho que ficaria mais fácil da gente construir.

**Comment by mbslet** [comment]
![screenshot from 2018-04-30 19-31-31](https://user-images.githubusercontent.com/30835147/39453638-2c938eaa-4cad-11e8-8fda-d4a2f3e65592.png)

Saberia que erro de API é esse? Estamos tentando usar o DayOfMonth e o MonthDay, existentes no java, ai aparece isso...

**Comment by aleronupe** [comment]
Pessoal, está rolando uma dificuldade em implementar o segmented control. Procuramos alguns códigos que auxiliem na inserção desse tipo de button no android, mas não sabemos se as modificações necessárias para a implementação desse método deve ser de grande escala (adicionando bibliotecas, módulos, inserindo arquivos no build.gradle) Ou se, para o escopo dessa issue, é algo mais parecido com um conjunto de elementos nativos do Android studio.

**Comment by gabrielalbino** [comment]
@mbslet isso só é suportado nos androids mais recentes, nosso app é feito pro nougat. Não dá pra usar o [Date](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.js/-date/index.html)?

**Comment by gabrielalbino** [comment]
@aleronupe já viu [esse](https://medium.com/@staceypyee/revealing-the-magic-of-creating-ios-segmented-control-with-image-in-android-kotlin-part-1-7d817f9d5c7)? Ele implemetna o segmented sem usar nenhuma dependência externa, você só mudaria a funcionalidade.

**Comment by mbslet** [comment]
@gabrielalbino Resolvi essa dúvida no slack mesmo, obri bino

**Comment by aleronupe** [comment]
@guibaldissera @Geovannioj @miguelpimentel @luis-gustavo Estamos com dificuldade em modificar as cores dos botões pelo jeito que colocamos, alguém pode dar uma ajuda?

**Comment by luis-gustavo** [comment]
Alexandre, ainda não pesquisei isso a fundo mas vê se existe a propriedade tintColor e se existir tenta alterá-la.

Se der certo/errado me avise

**Comment by aleronupe** [comment]
Não era bem isso, mas conseguimos aqui, valeu! :)

**Comment by luis-gustavo** [comment]
Boa!!

**Comment by aleronupe** [comment]
Senhores, temos um problema, mas eu tenho a solução: Todos os elementos em tela são células de uma _recycler view_ , de forma que quando usamos o _segmented control_ rola um _notifyDatsetChanged()_ e aí o programa recarrega todas as células. Até ai tudo bem, o único problema é que a animação do _segmented control_ se perde, pq como é recarregado tudo, a célula em que ela está também.  A minha solução é colocar essa célula com o _segmented control_ na activity, fora da _recycler view_ . O Que vocês sugerem? @luis-gustavo @guibaldissera @miguelpimentel @Geovannioj

**Comment by luis-gustavo** [comment]
Essa parece ser a melhor solução mesmo @aleronupe. Manda ver.

**Comment by guibaldissera** [comment]
Não é uma boa não man, você não deveria atualizar a recicler view inteira nesse caso. Você precisa atualizar apenas os índices que foram alterados e inseridos.

**Comment by aleronupe** [comment]
Sim, o problema é que o tamanho da _recycle view_ varia de acordo com o número de sets selecionado, daí é preciso verificar quais elementos são retirados e quais são atualizados

**Comment by aleronupe** [comment]
![image](https://user-images.githubusercontent.com/37146204/39660415-e9bc6faa-5014-11e8-9fed-21235aed74e3.png)
Pessoal, sabem como consertar esse erro que está ocorrendo no pipeline? É a única coisa que nos impede de dar o pull request!
