### ISSUE TITLE
Eu, como usuário, desejo adicionar um comentário a uma atividade do feed.

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#115]
## Descrição

Essa issue tem como objetivo adicionar um campo, na parte inferior da tela, para escrever um comentário e adicioná-lo na lista de comentários de uma atividade específica do feed. 

## Critérios de Aceitação

- [x] Adicionar campo para input de texto do usuário;
- [x] O campo inserção deve ficar sempre visível ao usuário, mesmo quando o teclado é mostrado;
- [x] Ao clicar no botão de adicionar o comentário, ele deve ser inserido na list view;
- [x] Ao clicar no botão de adicionar o comentário, deve-se limpar o campo de input.

**Comment by guibaldissera** [comment]
Aqui mostro um exemplo de como deve ficar ao clicar no input de comentário.
![img_0734](https://user-images.githubusercontent.com/17801101/39398079-f58a7646-4ade-11e8-8a63-68ea51efd33c.PNG)
![img_0735](https://user-images.githubusercontent.com/17801101/39398080-f5ac7b1a-4ade-11e8-87b8-f33d6d4aff55.PNG)

**Comment by luis-gustavo** [comment]
Passando parâmetro para outra activity.

https://stackoverflow.com/questions/2405120/how-to-start-an-intent-by-passing-some-parameters-to-it?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
