### ISSUE TITLE
Eu, como usuário, desejo desafiar o tenista selecionado na lista de tenistas disponíveis.

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#116]
## Descrição

Essa issue destina-se a adicionar um botão para desafar o tenista selecionado na tela de lista de tenistas disponíveis e mostrar um alerta de que o desafio foi enviado ao tenista após clicar nesse botão de desafiar.

## Critérios de Aceitação

- [ ] Deve-se adicionar um botão na tela de lista de tenistas;
- [ ] Esse botão deve estar como padrão, não enabled, e ao selecionar algum tenista, esse botão deve ficar enable.
- [ ] Ao clicar no botão, deve-se mostrar um alerta informando que o tenista tal foi desafiado.

**Comment by aleronupe** [comment]
@guibaldissera @luis-gustavo essa issue não era assigned pra @larissa-sales e pra @helenagoulart ???

**Comment by gabrielalbino** [comment]
@larissa-sales 
http://chintanrathod.com/display-alert-on-back-button-pressed-in-android-studio/

**Comment by gabrielalbino** [comment]
O contexto é meio diferente mas dá pra tirar uma ideia e ele explica a classe direitinho

**Comment by gabrielalbino** [comment]
Qualquer duvida manda aqui
