### ISSUE TITLE
Eu, como usuário, desejo visualizar desafio enviado

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#120]
## Descrição

Essa issue tem como objetivo gerar um um desafio após selecionar um tenista, criando na outra aba de desafio enviado, esse novo desafio.

## Critérios de Aceitação

- [x] Gerar ação ao clicar no botão de desafiar tenista;
- [x] Adicionar uma nova aba na tela de desafios, mantendo 3 abas no total (Tenistas, Enviado, Recebido);
- [x] Inabilitar o botão de desafiar para ele não enviar um desafio novamente;
- [x] Mostrar uma label com "Você já enviou um desafio", em caso de já ter enviado o desafio.
- [x] Na aba de Desafio Enviado, deve aparecer uma Label "Nenhum desafio enviado", caso ele ainda não tenha desafiado algum tenista.
- [x] Enviar a tela mostrada para a aba de Desafio Enviado após desafiar o tenista, mostrando o desafio enviado.

**Comment by gabrielalbino** [comment]
@guibaldissera @miguelpimentel precisa usar o servidor pra essa issue? e se eu entendi bem,
![image](https://user-images.githubusercontent.com/30835149/40031458-2e926d10-57c6-11e8-9147-9f216797ef29.png)
essa é a cena que vai ficar na aba "enviados"
![image](https://user-images.githubusercontent.com/30835149/40031494-4efb3f5a-57c6-11e8-868d-ccaba02c99b9.png)
essa vai ficar na de "recebidos"
![image](https://user-images.githubusercontent.com/30835149/40031515-67118ca2-57c6-11e8-928d-8c0f9115167a.png)
e essa na de "tenistas"
certo?
eu preciso implementar a de "recebidos"?
se sim, como ela deve ficar?

**Comment by miguelpimentel** [comment]
@gabrielalbino e @lorranyh, neste  momento não vamos trabalhar com o servidor. A partir da próxima semana começaremos a integrar nosso _backend_ e _frontend_. A tela com "melhor de" e o número de _sets_ refere-se a aba de recebidos. Já a tela com o botão de enviar desafios estar na aba  de enviados. Vou enviar como está no iOS agora. 

[![IMG_053_E261_BC49_C-1.jpg](https://s7.postimg.cc/lutvsdc2j/IMG_053_E261_BC49_C-1.jpg)](https://postimg.cc/image/7bmqqyixj/)

[![IMG_2399.png](https://s7.postimg.cc/r7iq6jpp7/IMG_2399.png)](https://postimg.cc/image/gxgb7aztj/)

**Comment by gabrielalbino** [comment]
@miguelpimentel essa n seria a de tenistas?
No critério tá pedindo 3 abas

**Comment by guibaldissera** [comment]
O @miguelpimentel não está atualizado sobre as coisas hahahaha
@gabrielalbino então, você fará 3 abas, conforme o critério de aceitação.
* Na primeira aba, você coloca como título "Tenistas", ela vai ter a lista dos tenistas disponíveis para desafiar;
* Na segunda aba, título "Enviado", vai mostrar as informações do desafio enviado, que é exatamente a tela que você mostrou na pergunta, a tela feita pelo Alexandre e Letícia;
* Na terceira aba, título "Recebido", vai ficar em branco no momento. Se quiserem mostrar também a mesma tela, de desafio, podem mostrar... A única diferença entre a aba "Enviado" e "Recebido" é que um o usuário logado é o desafiante, e no outro o usuário logado é o desafiado, com tenistas oponentes diferentes. Mas isso não está no critério de aceitação dessa Issue.

- O ponto é: a tela de desafio enviado, só pode mostrar a fragment de desafio, caso na aba de tenistas o usuário tenha selecionado alguém para desafiar e tenha desafiado.

Será que consegui responder?

**Comment by lorranyh** [comment]
@guibaldissera vai ser necessário criar um singleton com o desafio enviado?
