### ISSUE TITLE
Eu, como desenvolvedor, desejo aplicar design à lista de comentários, para que ela atenda aos requisitos de design

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#124]
## Descrição

Essa issue tem como objetivo aplicar o design na tela de lista de comentários seguindo o design desenvolvido pela Designer. Entregue na plataforma Zeplin.

## Critérios de Aceitação

- [ ] O design da lista de comentários deve seguir todos os dados, cores e espaçamentos do Design Oficial.
- [ ] Ajustar a Bottom Navigation conforme o Design.

**Comment by mbslet** [comment]
No design do zeplin não tem opção de denuncia e excluir comentario, e no nosso tem, ai coloca mesmo assim?

**Comment by luis-gustavo** [comment]
Colocar o que, @mbslet  ?

**Comment by luis-gustavo** [comment]
Aplica o design do que tem no zeplin até o momento, não se preocupa tanto com denunciar e excluir comentário. Só não deixa eles muito destoantes do resto do design da tela, tenta deixar nas mesmas cores/padrões.

Se houver alguma mudança, avisamos aqui.

**Comment by lorranyh** [comment]
É porque o design no Zeplin não aparece o botão de excluir comentário e denunciá-lo, apenas o de responder ao comentário, ai ficamos na dúvida sobre o que iríamos fazer com eles, mas deixaremos no xml, com uma estética melhor, obrigada @luis-gustavo .

**Comment by luis-gustavo** [comment]
De nada. Qualquer dúvida só falar.

**Comment by mbslet** [comment]
Segundo o design do zeplin, na parte de adicionar um comentário, tem um "certo" na direita e uma seta tipo do instagram na esquerda kk ai quero saber se essa seta é um botão de anexar alguma coisa e o certo é o de enviar

**Comment by mbslet** [comment]
Botão responder que no zeplin é um text, pode colocar para seguir o modelo certo?

**Comment by miguelpimentel** [comment]
Desculpa, a demora @mbslet e @lorranyh . Acabei fazendo trabalho e esqueci completamente.

**Comment by miguelpimentel** [comment]
Vou dar uma olhada nisso agora.

**Comment by miguelpimentel** [comment]
@guibaldissera  aqui:

* Não terá o botão "Responder". Coloca no lugar do "Responder", "Denunciar" ou "Excluir" caso o comentário seja do usuário logado;
* O botão de certo é o botão de enviar o comentário;
* O ícone estilo Direct do Instagram é apenas visual, não é um botão.

Detalhe, está um pouco confuso mesmo, iremos trocar uma ideia com a Designer hoje de tarde. Mas de antemão, sigam o que falamos hahahaha

**Comment by mbslet** [comment]
Galera, estamos tentando pegar os dados da Comments da Entities, ai ta rolando uma dúvida porque na classe da Comment tem os atributos como id, userId, comment e date. Ai existe uma classe Comment dentro da CommentModel também, com os dados diferentes, e a CommentFormated que formata os dados de acordo com essa classe da Model, porém eu deveria usar da Entities certo? E quando tento passar da Entities  para Formated, fica meio estranho e não ta fazendo muito sentido pra nós, queria um help pra entender melhor... Tipo, eu apaguei meus dados da Worker e usei a CommentManager pra pegar os outros dados mockados, mas na Presenter eu to bem confusa

**Comment by lorranyh** [comment]
@luis-gustavo eu devo mudar o tipo da response na model do newcomment pro tipo da entities do comment também?

**Comment by luis-gustavo** [comment]
Se ele era do tipo Comment(que estava na propria model), sim.

**Comment by lorranyh** [comment]
@luis-gustavo o tipo dele era daquela classe que foi apagada, coloquei de acordo com a entities

**Comment by luis-gustavo** [comment]
Show, isso mesmo.

**Comment by mbslet** [comment]
![oie_vc9oqpcq7tmc](https://user-images.githubusercontent.com/30835147/40560987-f81645b2-6031-11e8-962a-13eb2c055bc1.png)

**Comment by mbslet** [comment]
![oie_dyuhozxzhlxt](https://user-images.githubusercontent.com/30835147/40561044-24fcb674-6032-11e8-99a1-d23fb7192820.png)

**Comment by guibaldissera** [comment]
* Não é necessário sempre fazer o getAll, pelo que entendi, vocês querem inserir um novo comentário, então buscar os já existentes não se faz necessário; Isso só é necessário se vocês precisarem da lista toda para mostrar na tela novamente, mas daí isso é feito após a inserção...

* Pra inserir no banco, usando a commentManager, você precisa usar um comment do tipo Comment da Entity, ele provavelmente não usa o CommentsModel.Player()

* Se você for notar, ao final vocês estão chamando o mesmo método da função *getCommentsData*, que seria *updateLogic?.updateComment(response)*, se analisarmos mais a fundo, o updateComment recebe um tipo específico de response, e vocês estão criando outro tipo, na linha 57... isso gera o erro falando que o response está errado.

Vejam se entendem kkkk

**Comment by mbslet** [comment]
Então para eu adicionar um novo comentário poderia usar o método createCommentsIds() ?

**Comment by luis-gustavo** [comment]
Não, para criar um novo comentário é só utiizar o método update() da CommentManager. Só lembra de passar um novo id nesse comentário, pq se passar um id já existente ele vai apenas atualizar esse comentário.

**Comment by guibaldissera** [comment]
Isso, exatamente o que o @luis-gustavo comentou... é esse método aí abaixo

<img width="364" alt="captura de tela 2018-05-25 as 16 23 14" src="https://user-images.githubusercontent.com/17801101/40562586-f53a772c-6037-11e8-8aac-158a6edf47b5.png">

**Comment by mbslet** [comment]
![screenshot from 2018-05-25 16-31-58](https://user-images.githubusercontent.com/30835147/40562892-3770baec-6039-11e8-8928-60baff614072.png)
Então, essa e outras vezes quando uso a comment ai, ele espera receber algo nela, mas não ta dizendo o que

**Comment by luis-gustavo** [comment]
Tá esperando receber um objeto do tipo Comment. Igual na imagem que o @guibaldissera enviou
