### ISSUE TITLE
Eu, como usuário, desejo visualizar o ranking com um design mais bonito e usual

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#126]
## Descrição

Essa issue tem como objetivo aplicar o design na tela de ranking seguindo o design desenvolvido pela Designer. Entregue na plataforma Zeplin.

## Critérios de Aceitação

- [ ] O design do ranking deve seguir todos os dados, cores e espaçamentos do Design Oficial;
- [ ] A célula expandida também deve seguir o design.

**Comment by mbslet** [comment]
Gente, ainda estou trabalhando com os dados mockados né? Tudo o que tem na worker e tals... Pergunto pq existe uma conexão com o server já né, não sei kaka

**Comment by gabrielalbino** [comment]
sim, tudo mockado

**Comment by miguelpimentel** [comment]
@mbslet só vi agora, apaguei, estou meio dodói. Sim, essa semana vamos apenas trabalhar com os dados mocados. Nessa reunião da semana vou mostrar um pouquito sobre o Fuel e como lidar com as requsições http ao nosso servidor. Essa próxima _sprint_ vai ser top. @gabrielalbino, muito bom, sempre atenado, é nois lindão.

**Comment by mbslet** [comment]
Como esses circulos de vitórias, derrotas e invictos foram feitos para ios?

**Comment by miguelpimentel** [comment]
@mbslet, desculpa a demora. Fiquei atolado no trabalho hoje e acabei esquecendo. Então, a gente fez com views pequenas e utilizamos o cornerRadius para fazer essas curva. O cornerRadius é uma propriedades própria desse elemento de UI. Deve ter algo parecido no Android. Vou  olhar aqui para você.

**Comment by miguelpimentel** [comment]
Uma forma interessante que achei é criar um shape que poderia receber o nome de Circle, por exemplo, como isso:

```


down vote
shape.xml

<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">

    <solid android:color="#f6eef1" />

    <stroke
        android:width="2dp"
        android:color="#000000" />

    <padding
        android:bottom="5dp"
        android:left="5dp"
        android:right="5dp"
        android:top="5dp" />

    <corners android:radius="5dp" />

</shape>
```

E utilizá-lo, fazendo referência a esse xml, onde referência o shape, está vendo: 

```<LinearLayout
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="10dp"
        android:layout_marginRight="10dp"
        android:layout_marginBottom="10dp"
        android:clipChildren="true"
        android:background="@drawable/shape">

        <ImageView
             android:layout_width="match_parent"
             android:layout_height="match_parent"
             android:src="@drawable/your image"
             android:background="@drawable/shape">  

</LinearLayout>
```

**Comment by miguelpimentel** [comment]
Isso aqui que achei é melhor

```

<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <solid
        android:color="#48b3ff"/>
</shape>

```

**Comment by miguelpimentel** [comment]
https://stackoverflow.com/questions/3185103/how-to-define-a-circle-shape-in-an-android-xml-drawable-file

**Comment by mbslet** [comment]
Eu fiz isso, mas quando coloco o tamanho menor tava dando bug... Vou ver se acho o problema então, obrigadaa!
