### ISSUE TITLE
Eu, como desenvolvedor, desejo aplicar o design à lista de curtidas para que ela fique mais atrativa

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#128]
## Descrição

Essa issue tem como objetivo aplicar o design na tela de lista de curtidas seguindo o design desenvolvido pela Designer. Entregue na plataforma Zeplin.

## Critérios de Aceitação

- [ ] O design da lista de curtidas deve seguir todos os dados, cores e espaçamentos do Design Oficial;

**Comment by guibaldissera** [comment]
<img width="322" alt="captura de tela 2018-05-27 as 16 15 40" src="https://user-images.githubusercontent.com/17801101/40589745-58f6fc58-61c9-11e8-826d-e8ab02b1d5d9.png">
