### ISSUE TITLE
Eu, como desenvolvedor, desejo atualizar o arquivo .gitignore para não incluir arquivos indesejáveis

### ISSUE THREAD

**Issue by larissa-sales** [fga-gpp-mds/2018.1_Nexte#153]
## Descrição

Há arquivos que não são necessários para o funcionamento do projeto

## Critérios de Aceitação

 - [ ] Não ignorar arquivos necessários pro projeto

**Comment by luis-gustavo** [comment]
Fechando esse pull request pois já foi resolvido
