### ISSUE TITLE
Eu, como desenvolvedor, desejo saber como utilizar o viewModel com a listview para implementar o histórico

### ISSUE THREAD

**Issue by gabrielalbino** [fga-gpp-mds/2018.1_Nexte#158]
## Descrição
@miguelpimentel @guibaldissera @Geovannioj  @luis-gustavo 

Gostaria de saber como que ficaria a viewModel com a listView

Uma solução que eu pensei foi ter

````kotlin
class ViewModel {
    var adapter : BaseAdapter
    constructor(adapter: BaseAdapter) {
        this.adapter = adapter
    }
}
````

Pois como a presenter é responsável por formatar os dados para a Activity (que seria nossa view), eu já deveria mandar o adapter (teria que implementar a classe abstrata BaseAdapter em alguma classe aninhada à presenter) pra simplesmente associa-lo ao adapter da view depois assim: 

Na Presenter:
````kotlin
val adapter = MyImplementedAdapter(someArg1, someArg2)
viewModel = HistoryModel.ViewModel(adapter)
HostoryDisplayLogic.updateListViewData(viewModel)
````

Na updateListViewData:
````kotlin
someViewList.adapter = viewModel.adapter
````

essa sulução seria viável? ou vocês recomendam algo diferente?
 
[Aqui](http://scottmmjackson.com/learning-kotlin-simple-listview-adapter/) tem uma explciação sobre o adapter

## Critérios de Aceitação
Não se aplica.

**Comment by miguelpimentel** [comment]
@gabrielalbino , parabéns! Muito boa sua iniciativa, foi muito bom mandar isso porque não conhecia o anko do Kotlin e nem o "Adapter"nessa linguagem. Pelo que entendi, o adaptar seria para fazer uma interface de forma que ela gerencie os recursos de forma mais eficiente que seria apresentados numa ListView, certo? E sua solução seria implementar esse adapter como uma classe aninhada da presenter para instanciar um objeto do tipo desse adapter e já enviar para a View. Então, a View receberia esse adapter(View model) e apresentaria na ListView, correto? Se for isso, acho interessante. Esse adaptar iria possuir todos os tipos básicos que seria consumidos pela List View? Se sim, essa implementação é muito bem vinda, principalmente pelo gerenciamento de recursos. Da forma que colocou não fere nossa arquitetura.  Estou de acordo.

**Comment by gabrielalbino** [comment]
@miguelpimentel a adpter é basicamente responsável por pegar um xml de layout, transformar numa view (o xml conteria o layout de cada linha da listView, e cada view seria uma linha da listView), e preencher o conteúdo das views (ex: fotos, textos e botões) com o conteúdo especifico de cada linha da listview através do método sobre-escrito getView.
Vou tentar realizar essa implementação então, qualquer empecilho aviso vocês

**Comment by miguelpimentel** [comment]
Isso mesmo. ele atua como uma interface entre o modelo de dados e a View. É diferente do Adapter(Gof pattern). No nosso caso poderia ser o man in the middle entre response e ViewModel, sendo que concordo e apoio sua abstração. Só uma coisa, você tá usando o anko? Se possível evita, é uma dependência desnecessária nesse momento, quanto menos dependências melhor. Tem esse tutorial aqui que ele usa um adapter e não usa do Anko. https://www.raywenderlich.com/186976/android-listview-tutorial-2

**Comment by luis-gustavo** [comment]
@gabrielalbino tudo certo em relação a esse problema ? Alguma dúvida ainda ? Caso esteja tudo certo em relação a esse problema pode fechar essa issue.

**Comment by gabrielalbino** [comment]
Tudo certo, a solução é funcional.

**Comment by guibaldissera** [comment]
@miguelpimentel @gabrielalbino 
Senhores, bora lá... kkkkkk
Muito bom toda essa discussão, realmente parabéns por achar uma boa forma de utilizar listView.
Porém, vamos lá...

- A presenter de fato tem como objetivo formatar os dados para serem mostrados na view.
- Essa classe de adapter, faz uso de um Context, esse negócio é totalmente referente a view, ou a activity. Isso é View e não formatação de dados.
- Naquele método de getView() padrão do Adapter, ele faz total referência ao XML, isso em teoria não pode estar na Presenter.
- Em minha visão, acredito que a viewModel de vocês teria um array de player com seus atributos todos em Strings, passando isso para a view, e a view faria essa conversão para o adapter.

@miguelpimentel isso é basicamente um TableViewDataSource do Swift, com os métodos de cellForRowAt (getView do android), numbersOfRowsInSection (getCount no android) e assim sucessivamente.

O que tu me diz?
Acredito que esses métodos devem ficar na RankingActivity, e na verdade é só implementar o BaseAdapter direto na RakningActivity, sem a necessidade de criar outra classe (RankingAdapter) para isso.

**Comment by gabrielalbino** [comment]
Realmente faria mais sentido enviar os dados formatados em string e só
associa-los á row na view, aí impediria o context de viajar por todas a
camadas p chegar na presenter

Em Sex, 6 de abr de 2018 02:04, Guilherme Baldissera <
notifications@github.com> escreveu:

**Comment by miguelpimentel** [comment]
@guibaldissera, valew. Eu tava olhando ontem os PR's e tava achando muito estranho. @gabrielalbino, acho que seria mais legal fazer isso na Activity. E para ficar mais legal você poderia criar uma interface no mesmo arquivo com os métodos e variáveis que iria utilizar na implementação do adapter, semelhante ao que Swift faz. @gabrielalbino, quando o @guibaldissera falou sobre TableViewDataSource e TableViewDelegate ambos são implementados como interfaces(protocolos) para diminuir o acoplamento.

**Comment by guibaldissera** [comment]
Vou fechar essa issue.
O código com a arquitetura correta exemplo será disponibilizado pela feature/97 na Feed Scene
