### ISSUE TITLE
Eu, como Desenvolvedor, gostaria de criar o protótipo de alta fidelidade utilizando Marvel.

### ISSUE THREAD

**Issue by guibaldissera** [fga-gpp-mds/2018.1_Nexte#169]
## Descrição

Essa issue terá como objetivo pegar as telas exportadas pelo grupo Nexte, adiciona-las ao Marvel e fazer um protótipo de alta fidelidade para exemplificar o funcionamento do aplicativo e para testar as funcionalidades.

## Critérios de Aceitação

- [x] Criar projeto no Marvel;
- [x] Ter interação com o protótipo gerado;
- [x] Usar as telas exportadas pelo Nexte.

**Comment by guibaldissera** [comment]
![simulator screen shot - iphone x - 2018-03-07 at 00 53 12](https://user-images.githubusercontent.com/17801101/38461995-25e897e4-3ab5-11e8-9bc4-79c74a1cb81c.png)
![simulator screen shot - iphone x - 2018-03-07 at 00 53 16](https://user-images.githubusercontent.com/17801101/38461996-26078226-3ab5-11e8-9442-0320db79c1e9.png)
![simulator screen shot - iphone x - 2018-03-07 at 00 53 27](https://user-images.githubusercontent.com/17801101/38461997-2626746a-3ab5-11e8-971c-be495a6d7b5a.png)
![simulator screen shot - iphone x - 2018-03-07 at 00 53 33](https://user-images.githubusercontent.com/17801101/38461998-2644688a-3ab5-11e8-8b2e-1691f5b2f840.png)
![simulator screen shot - iphone x - 2018-03-07 at 00 53 39](https://user-images.githubusercontent.com/17801101/38461999-2663b2ee-3ab5-11e8-8409-e10ef817776c.png)
![simulator screen shot - iphone x - 2018-03-07 at 21 33 32](https://user-images.githubusercontent.com/17801101/38462000-26830608-3ab5-11e8-9dfc-eacf581e5036.png)
![simulator screen shot - iphone x - 2018-03-07 at 22 50 39](https://user-images.githubusercontent.com/17801101/38462001-26a01f72-3ab5-11e8-9240-6933d04d870b.png)
![simulator screen shot - iphone x - 2018-03-07 at 22 51 00](https://user-images.githubusercontent.com/17801101/38462002-26bc5d36-3ab5-11e8-8e7a-3a62ae9e99e4.png)
![simulator screen shot - iphone x - 2018-03-07 at 22 51 13](https://user-images.githubusercontent.com/17801101/38462003-26d98d48-3ab5-11e8-962e-01773d069592.png)
![simulator screen shot - iphone x - 2018-03-07 at 22 51 21](https://user-images.githubusercontent.com/17801101/38462004-26f6d20e-3ab5-11e8-816c-e68aea41b63e.png)

**Comment by gabrielalbino** [comment]
@guibaldissera manda print do ranking exibindo os primeiros do ranking também (sem expandir a celula de nenhum)

**Comment by guibaldissera** [comment]
Aí @gabrielalbino 
![simulator screen shot - iphone x - 2018-04-09 at 21 51 34](https://user-images.githubusercontent.com/17801101/38530326-39518ade-3c40-11e8-99ee-aaf1b3cd2c55.png)

**Comment by gabrielalbino** [comment]
@guibaldissera precisa fazer o diagrama igual no protótipo de baixa fidelidade? ou so o marvel tá show?
