### ISSUE TITLE
Teste unitários para classe View

### ISSUE THREAD

**Issue by luis-gustavo** [fga-gpp-mds/2018.1_Nexte#184]
## Descrição
Para testar a classe View de cada cena, deve-se testar métodos como o onCreate() ?. Outra dúvida seria, como/faz sentido realizar testes de métodos que estão ligados ao xml ?

## Critérios de Aceitação
Não se aplica.

**Comment by guibaldissera** [comment]
Métodos específicos de View serão testados possivelmente no Instrumental Test.
É possível testar alguns métodos menos ligados a View ou então, instanciá-la e verificar se os métodos chamados no onCreate foram chamados. Validando assim o funcionamento do onCreate.

Em Swift, testamos da seguinte forma:

<img width="783" alt="captura de tela 2018-04-11 as 20 56 45" src="https://user-images.githubusercontent.com/17801101/38649134-42a92f10-3dcb-11e8-87ae-46d959064f09.png">
Na imagem de cima, é instaciada a View e na hora dos testes, é setada a interactor spy para simulá-la, chamada a criação da tela na window, e então validado se os métodos presentes originalmente no "onCreate" do swift foram chamados. 

Para criar a interactor spy, foi usada essa classe da imagem abaixo:
<img width="562" alt="captura de tela 2018-04-11 as 20 57 01" src="https://user-images.githubusercontent.com/17801101/38649135-42c7162e-3dcb-11e8-9255-03eab1399a32.png">

**Comment by luis-gustavo** [comment]
https://developer.android.com/training/testing/unit-testing/local-unit-tests.html

Pra resolver isso em android é necessário uma framework estilo [mockito](http://site.mockito.org/).

Vou planejar para sprints futuras um treinamento sobre isso
