### ISSUE TITLE
Eu, como desenvolvedor, preciso atualizar o documento de arquitetura para que a documentação da arquitetura do projeto reflita a real arquitetura aplicada

### ISSUE THREAD

**Issue by luis-gustavo** [fga-gpp-mds/2018.1_Nexte#192]
## Descrição

Após o desenvolvimento inicial, por dificuldade técnica da equipe, teve-se foco em desenvolvimento e entendimento do que estava sendo feito. Por esse motivo os documentos foram esquecidos. 
Portanto, essa issue tem como objetivo atualizar todos os documentos necessários para que entenda-se a atual situação do código.

## Critérios de Aceitação

- [x] Ajustar documentos mal formatados no GitHub Pages;
- [ ] Atualizar diagrama de classes no Documento de Arquitetura;
- [ ] Atualizar informações sobre as camadas no Documento de Arquitetura.

**Comment by gabrielalbino** [comment]
@miguelpimentel o [documento de microserviços](https://github.com/fga-gpp-mds/2018.1_Nexte/blob/feature/192/docs/EPS/ArquiteturaMicroservicos.md) está sem historico de revisão e com uma imagem quebrada. Favor corrigir isso na branch 192.

**Comment by miguelpimentel** [comment]
@gabrielalbino  todas as imagens que estavam hospedadas no postimg, estão quebradas. A do README, também está. Mas, eu criei uma issue para atualizar o micro serviço, esse documento será feito todo novo. Amanhã quando tiver um tempinho irei arrumar isso.

**Comment by miguelpimentel** [comment]
Mas, valew pela dica. Vamo que vamo.

**Comment by aleronupe** [comment]
As variáveis que instanciam objetos da model dentro de métodos devem ser consideradas como critério pra estabelecermos as relações de agregação/composição? Ou só definimos as relações para variáveis/parâmetros de classe?

**Comment by miguelpimentel** [comment]
Tipo isso @aleronupe ?

````
// Dentro de um fetch na worker

val response = Model.Response()
````

**Comment by miguelpimentel** [comment]
Se a variável for de escopo apenas do método não precisa.
