### ISSUE TITLE
Eu, como desenvolvedor, preciso refatorar o código seguindo as métricas de qualidade para que o código esteja seguindo os parâmetros de qualidade do projeto

### ISSUE THREAD

**Issue by luis-gustavo** [fga-gpp-mds/2018.1_Nexte#193]
## Descrição

Esta issue destina-se a aprimorar o código para que a Release 2 comece da melhor forma possível.

## Critérios de Aceitação

- [ ] Detekt estar rodando sem problemas e warnings;
- [ ] Documentar com detalhes, seguindo a Folha de Estilo;
- [ ] Seguir a folha de estilo por completo.

**Comment by helenagoulart** [comment]
@Geovannioj encontrei na LoginView tudo comentado com a descrição "Commented cause it should make reference to main view at this point". Nesse caso, o que faço? "Descomento" e arrumo na MainActivity?
