### ISSUE TITLE
Eu, como desenvolvedor, gostaria de ajustar o design para a primeira apresentação

### ISSUE THREAD

**Issue by luis-gustavo** [fga-gpp-mds/2018.1_Nexte#194]
## Descrição

Para a primeira release, seria interessante ajustar o design, aplicando cores, padronização de cores, etc.

## Critérios de Aceitação

- [x] Aplicar cores;
- [x] Padronizar fontes em todas as telas;
- [x] Simular TabBar com os três botões na parte inferior da tela.

**Comment by guibaldissera** [comment]
Estava olhando aqui no Projeto, já existe um arquivo específico que centraliza as cores do App, vejam nas imagens...
Assim, é fácil setar as cores nas telas, só fazer referências as criadas no colors.xml
<img width="225" alt="captura de tela 2018-04-16 as 21 24 57" src="https://user-images.githubusercontent.com/17801101/38841859-dcb56084-41bc-11e8-8f0d-7ba653dbc579.png">
<img width="423" alt="captura de tela 2018-04-16 as 21 25 11" src="https://user-images.githubusercontent.com/17801101/38841860-dcd392fc-41bc-11e8-83b6-324f2b398bb0.png">

**Comment by mbslet** [comment]
Só uma dúvida, temos o xml da history mas não há um packege dela. E no xml activity_history faz referência ao Feed. Fiquei meio confusa

**Comment by miguelpimentel** [comment]
Tudo que era da cena de History foi transformado na Feed. Na feed, reutilizamos o XML, entendeu o porquê da referência?  O package da Scene foi deletado.

**Comment by guibaldissera** [comment]
Qual imagem tu está se referindo?
