### ISSUE TITLE
Impossibilidade de integração com Slack

### ISSUE THREAD

**Issue by guibaldissera** [fga-gpp-mds/2018.1_Nexte#28]
@RochaCarla                        
Não estamos conseguindo integrar o repositório com aplicativos ou plugins externos como o ZenHubApp e com o Slack. Com Webhooks é possível, porém com as integrações oficiais não.

A imagem em anexo mostra que ali na aba lateral não contém o projeto.
Existe algum tipo de configuração que possa liberar isso? Algum tipo de privilégio que não temos devido ao repositório ser parte de uma organização?

![Captura de Tela 2018-03-14 às 18.02.56.png](https://images.zenhubusercontent.com/5aa1660e4b5806bc2bca062e/26dadafb-2923-4a8b-8120-a270c3c8be86)

**Comment by RochaCarla** [comment]
Qual o problema de se fazer os com webhooks?
Vou te colocar como owner do repositório.. mas a principio não era pra ter esse problema nao...

**Comment by RochaCarla** [comment]
vi aqui e vcs já estão como admin..

**Comment by guibaldissera** [comment]
Estamos tentando adicionar o GitHub ao Slack porém o repositório não aparece dentro os disponíveis para integração.
No Slack existe essa mensagem:
<img width="873" alt="captura de tela 2018-03-14 as 23 58 33" src="https://user-images.githubusercontent.com/17801101/37442223-d4c83b28-27e3-11e8-8fba-23753adfbe9c.png">

**Comment by guibaldissera** [comment]
Podemos utilizar a integração oficial do github com o slack sem a necessidade de criação de WebHooks garantindo a total interoperabilidade entre as plataformas.

**Comment by guibaldissera** [comment]
@RochaCarla

**Comment by guibaldissera** [comment]
Resolvido!
