### ISSUE TITLE
Eu, como desenvolvedor, desejo Elaborar README para fornecer uma idéia geral do aplicativo para o usuário.

### ISSUE THREAD

**Issue by luis-gustavo** [fga-gpp-mds/2018.1_Nexte#30]
## Descrição
Descrever o README desse projeto segundo esse template: https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

## Critérios de Aceitação
 - [ ] Todos os tópicos abordados no template forem descritos no readme
 - [ ] Adicionar licensa ao projeto

**Comment by larissa-sales** [comment]
Ficou um errinho no readme.... "Prerequisitos"
