### ISSUE TITLE
Eu, como gerente do projeto gostaria de fazer o Treinamento sobre Kotlin com a arquitetura a ser utilizada no projeto, para que a equipe de desenvolvimento seja treinada 

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#42]
## Critérios de Aceitação

 - [ ]  É preciso criar um documento contendo a arquitetura da cena que será criada
 - [ ]  É preciso ser implementada junto com a equipe de MDS alguma feature que será utilizada no app.
 - [ ] O código fonte deverá ser disponibilizado para o time de desenvolvedores
-  [ ] O treinamento deverá conter uma noção básica de Kotlin

**Comment by luis-gustavo** [comment]
@miguelpimentel Escreva a descrição da issue e os critérios de aceitação

**Comment by miguelpimentel** [comment]
Sim, adicionei, Obrigado por lembrar.
