### ISSUE TITLE
Eu como gerente do projeto gostaria de criar o documento de EVM para mensurar o desempenho desenvolvido

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#43]
## Descrição

A EVM é o que ajuda à verificar o andamento do projeto relacionado ao valor agregado do produto, além disso descreve o andamento do projeto em porcentagem de concluído ou não
## Critérios de Aceitação

 - [x] criar planilha de análise por _Sprints_
 - [x] Documento detalhado sobre como é a equação que vai calcular cada ponto a ser analisado
 - [x] Legenda das siglas a serem utilizadas na EVM

**Comment by luis-gustavo** [comment]
@Geovannioj Adicione a descrição e os critérios de aceitação dessa issue conforme o template proposto porfavor.

**Comment by Geovannioj** [comment]
Obg por lembrar, issue descrita de acordo com o template.
