### ISSUE TITLE
Eu, como desenvolvedor, quero implementar a cena arquitetural de exibir perfil para exibir as informações dos usuários do aplicativo

### ISSUE THREAD

**Issue by mbslet** [fga-gpp-mds/2018.1_Nexte#62]
## Descrição

Criar a arquitetura da tela de mostrar perfil

## Critérios de Aceitação

 - [x] Pacote individual da cena criada;
 - [x] Interactor precisa ser chamada na MainView;
 - [x] Precisa ser implementado DisplayLogic para imprimir uma mensagem no console;
 - [x] 3 interfaces (InteractorBusinessLogic (Interactor), PresentationLogic (Presenter) e DisplayLogic (View));
 - [x] 4 classes (Interactor, Model, Worker e Presenter).

**Comment by luis-gustavo** [comment]
@mbslet @gabrielalbino @lorranyh @larissa-sales @aleronupe @helenagoulart Falta atribuir o responsável por essa issue
