### ISSUE TITLE
Eu, como desenvolvedor, quero implementar a cena arquitetural do feed para exibir as partidas recentes no aplicativo

### ISSUE THREAD

**Issue by mbslet** [fga-gpp-mds/2018.1_Nexte#63]
## Descrição

Criar a arquitetura da tela de feed

## Critérios de Aceitação

 - [ ] Pacote individual da cena criada;
 - [ ] Interactor precisa ser chamada na MainView;
 - [ ] Precisa ser implementado DisplayLogic para imprimir uma mensagem no console;
 - [ ] 3 interfaces (InteractorBusinessLogic (Interactor), PresentationLogic (Presenter) e DisplayLogic (View));
 - [ ] 4 classes (Interactor, Model, Worker e Presenter).

**Comment by luis-gustavo** [comment]
@mbslet @gabrielalbino @lorranyh @larissa-sales @aleronupe @helenagoulart Falta atribuir o responsável por essa issue
