### ISSUE TITLE
Eu, como desenvolvedor, quero implementar a cena arquitetural da lista de comentários para exibir os comentários da partida do feed

### ISSUE THREAD

**Issue by mbslet** [fga-gpp-mds/2018.1_Nexte#65]
## Descrição

Criar a arquitetura da tela da lista de comentários

## Critérios de Aceitação

 - [ ] Pacote individual da cena criada;
 - [ ] Interactor precisa ser chamada na MainView;
 - [ ] Precisa ser implementado DisplayLogic para imprimir uma mensagem no console;
 - [ ] 3 interfaces (InteractorBusinessLogic (Interactor), PresentationLogic (Presenter) e DisplayLogic (View));
 - [ ] 4 classes (Interactor, Model, Worker e Presenter).

**Comment by luis-gustavo** [comment]
@mbslet @gabrielalbino @lorranyh @larissa-sales @aleronupe @helenagoulart Falta atribuir o responsável por essa issue

**Comment by luis-gustavo** [comment]
@larissa-sales essa histórias ainda está em "to do " ?
