### ISSUE TITLE
Eu, como desenvolvedor, quero implementar a cena arquitetural do desafio para efetuar a marcação de partidas

### ISSUE THREAD

**Issue by mbslet** [fga-gpp-mds/2018.1_Nexte#66]
## Descrição

Criar a arquitetura da tela de criar desafio

## Critérios de Aceitação

 - [ ] Pacote individual da cena criada;
 - [ ] Interactor precisa ser chamada na MainView;
 - [ ] Precisa ser implementado DisplayLogic para imprimir uma mensagem no console;
 - [ ] 3 interfaces (InteractorBusinessLogic (Interactor), PresentationLogic (Presenter) e DisplayLogic (View));
 - [ ] 4 classes (Interactor, Model, Worker e Presenter).

**Comment by luis-gustavo** [comment]
@mbslet @gabrielalbino @lorranyh @larissa-sales @aleronupe @helenagoulart Falta atribuir o responsável por essa issue

**Comment by luis-gustavo** [comment]
@aleronupe essa história ainda está em "to do " ?

**Comment by aleronupe** [comment]
Sim, vamos fazê-la amanhã, estamos fazendo uma por vez.

**Comment by aleronupe** [comment]
@luis-gustavo @Geovannioj @guibaldissera @miguelpimentel  pra facilitar a manipulação dos dados, é permitido a criação de uma classe "player" dentro do pacote? Em alguns casos, será necessário tratar o jogador como objeto com atributos de interesse para a cena, porém não sei se, por ser uma classe tão importante, deve ser criada em um pacote de cena ou em um pacote global

**Comment by miguelpimentel** [comment]
Seria legal, criar local. Nesse momento, não é legal ninguém criar algo
global.


Em 30 de março de 2018 01:37, Alexandre Miguel <notifications@github.com>
escreveu:
