### ISSUE TITLE
Eu, como DevOps, quero configurar a Integração Contínua ao repositório

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#67]
## Descrição
Essa issue destina-se a realizar uma configuração para integração contínua e geração de build do aplicativo automatizado ao ser enviado uma atualização aos repositórios do projeto com uma validação básica para build success ou fail invalidando o commit.
Futuramente deverá ser integrado validações segundo as métricas a serem definidas no plano de qualidade.

## Critérios de Aceitação

- [ ] Escolher qual plataforma utilizar para integrar ao github (Circle CI, Travis CI...)
- [ ] Criar .yml para execução na plataforma escolhida, integrando o Docker do projeto.
- [ ] Configurar o repositório para executar os pipelines pelo .yml.

**Comment by luis-gustavo** [comment]
@guibaldissera essa história ainda está em "to do"?
