### ISSUE TITLE
Eu, como desenvolvedor, quero Elaborar Documento de Arquitetura para me guiar no organização do projeto

### ISSUE THREAD

**Issue by luis-gustavo** [fga-gpp-mds/2018.1_Nexte#7]
## Descrição
O projeto deve possuir um documento de arquitetura, que servirá de base para para a construção do projeto, auxiliando os desenvolvedores que deverão seguir o padrão nele imposto.

## Critérios de Aceitação
- [ ] O documento deve estar totalmente preenchido e ser coerente
- [ ] Deve ser revisado por ao menos duas pessoas.

**Comment by luis-gustavo** [comment]
Não deve ter casos de uso/teste

**Comment by luis-gustavo** [comment]
@gabrielalbino Adicione descrição e critérios de aceitação dessa issue conforme o template proposto porfavor.

**Comment by gabrielalbino** [comment]
@luis-gustavo corrigido
