### ISSUE TITLE
Eu, como gerente do projeto, quero criar o contributing do repositório

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#70]
## Critérios de Aceitação

 - [ ] Exemplo: É preciso...
 - [ ] Exemplo2: Precisa ser feito...

**Comment by luis-gustavo** [comment]
@Geovannioj adicione descrição e critérios de aceitação para essa issue

**Comment by luis-gustavo** [comment]
Lembrando que aqui no contributing deve ir o "plano de gcs"(política de branches) e as métricas
