### ISSUE TITLE
Eu, como gerente do projeto, quero colocar a definição de pronto para pasta docs do projeto

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#72]
## Critérios de Aceitação

 - [ ] Exemplo: É preciso...
 - [ ] Exemplo2: Precisa ser feito...

**Comment by luis-gustavo** [comment]
@Geovannioj  adicione descrição e critérios de aceitação para essa issue

**Comment by luis-gustavo** [comment]
Ja tinha sido feito em sprints anteriores, não é mais válido
