### ISSUE TITLE
Eu, como gerente do projeto desejo escrever as histórias de usuário que faltam no projeto, para ter um backlog e não de features para serem feitas.

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#94]
## Critérios de Aceitação

 - [ ] Exemplo: É preciso...
 - [ ] Exemplo2: Precisa ser feito...

**Comment by luis-gustavo** [comment]
@Geovannioj colocar aqui critérios de aceitação e descrição

**Comment by luis-gustavo** [comment]
@Geovannioj mesmo já tendo terminado, coloque os critérios de aceitação e descrição.
