### ISSUE TITLE
Eu, como DevOps, desejo averiguar a cobertura de código do projeto na Integração contínua, para saber a porcentagem do código que está coberto por testes

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#96]
## Descrição
Escolher a ferramenta para cobertura de código e implementa-la no projeto 

## Critérios de Aceitação

 - [x] Escolher ferramenta para averiguar cobertura de código
 - [ ] Colocar ferramenta no código

**Comment by luis-gustavo** [comment]
@Geovannioj colocar descrição e critérios de aceitação
