### ISSUE TITLE
Eu, como gerente do projeto, desejo realizar treinamento de Kotlin para o time de desenvolvimento para sanar dúvidas do time

### ISSUE THREAD

**Issue by Geovannioj** [fga-gpp-mds/2018.1_Nexte#97]
## Descrição

Treinamento com kotlin a respeito de boas práticas e uso de alguns componentes de Layout

## Critérios de Aceitação

 - [ ] Criar Slides
 - [ ] Apresentar conteúdo e tirar dúvidas com o time de desenvolvedor

**Comment by luis-gustavo** [comment]
@miguelpimentel colocar descrição e critérios de aceitação

**Comment by guibaldissera** [comment]
Senhores, aí tem 2 links sobre recycler view... O primeiro é o que foi usado para aplicar ao nosso contexto. Deem uma olhadinha aí
https://medium.com/collabcode/criando-lista-com-recyclerview-no-android-com-kotlin-85cb76f3775d
https://www.raywenderlich.com/170075/android-recyclerview-tutorial-kotlin
